objects/Account.object
<CustomObject>
    <fields>
        <fullName>ERPSystem__c</fullName>
        <description>This will determine which ERP to sync the Customer Account.</description>
        <inlineHelpText>This will determine which ERP to sync the Customer Account.</inlineHelpText>
        <label>ERP System</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ERPSystem</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subsidiary__c</fullName>
        <description>This is used to map the global subsidiaries</description>
        <label>Subsidiary</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GlobalSubsidiaries</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>This represents that Account created is a Customer Account</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Agent_Satisfaction_Score__c</fullName>
        <label>Agent Satisfaction Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Dispute</fullName>
        <active>true</active>
        <businessProcess>TAC</businessProcess>
        <description>This is to create a dispute case with TKWW</description>
        <label>Dispute</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Contracted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag used to kick off automatic asset and subscription conversion.</description>
        <inlineHelpText>Salesforce CPQ uses this field to automatically convert assets and subscriptions.</inlineHelpText>
        <label>Contracted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag that drives automatic order creation.</description>
        <inlineHelpText>Select this checkbox to automatically create an order from the primary quote.</inlineHelpText>
        <label>Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to primary quote on this opportunity.</description>
        <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
        <label>Primary Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>PrimaryOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>ERPSystem__c</fullName>
        <formula>TEXT(Account.ERPSystem__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ERP System</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contracted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the order is contracted.</description>
        <inlineHelpText>Indicates if the order is contracted.</inlineHelpText>
        <label>Contracted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subsidiary__c</fullName>
        <formula>TEXT(Account.Subsidiary__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subsidiary</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__ChargeType__c</fullName>
        <description>The type of the product charge.</description>
        <inlineHelpText>The type of the product charge.</inlineHelpText>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__ChargeType</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag to drive automatic order creation.</description>
        <inlineHelpText>Select this checkbox to automatically create an order from this quote, if it is a primary quote.</inlineHelpText>
        <label>Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__PriceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Price Book associated with this Quote.</description>
        <inlineHelpText>Price Book associated with this Quote.</inlineHelpText>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__SalesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales rep responsible for this quote if different from the user who owns the quote record.</description>
        <inlineHelpText>Sales rep responsible for this quote if different from the user who owns the quote record.</inlineHelpText>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__ChargeType__c</fullName>
        <description>The type of the product charge.  This is a system field that is derived from the associated product.</description>
        <inlineHelpText>The type of the product charge.  This is a system field that is derived from the associated product.</inlineHelpText>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__ChargeType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__PricebookEntryId__c</fullName>
        <label>Pricebook Entry Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/ERPSystem.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>NetSuite</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Cloud</fullName>
    </customValue>
    <masterLabel>ERP System</masterLabel>
</GlobalValueSet>

globalValueSets/GlobalSubsidiaries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HT US Newyork</fullName>
    </customValue>
    <customValue>
        <fullName>HT US San Francisco</fullName>
    </customValue>
    <customValue>
        <fullName>HT Northern IRE</fullName>
    </customValue>
    <customValue>
        <fullName>HT Mainland IRE</fullName>
    </customValue>
    <description>This</description>
    <masterLabel>Global Subsidiaries</masterLabel>
</GlobalValueSet>

classes/Sample.cls
public class Sample {
    
    public static void createData(){
        /*
        * This script creates data for Account, Opportunity & OpportunityLineItems
        * @Author : Jade Global
        * 
        */
        
        /*
        1. Create Accounts for different countries and users
        */ 
        list<Account> lstAccToInsert = new list<Account>();
        list<id> lstAccId = new list<id>();
        list<string> lstAccName = new list<string>();
        /*list<string> lstCountry = new list<string>{'Germany', 'Greenland', 'India', 'Canada', 
            'Iceland', 'Macao', 'Taiwan', 'China', 'Japan', 
            'Jersey', 'Australia','Russia', 'China' ,'Norway',
            'Argentina','Chile', 'Peru','Brazil','Colombia','France'
            };*/
                
        list<string> lstCountry = new list<string>{'Germany'};     
        // Query the active user that are having role assigned from system
        list<User> lstUser = [select id, Name from User where UserRoleId != null and isActive = true];
        
        for(string country: lstCountry){
            for(User usr: lstUser){  
                if(usr.Name != 'Integration User' && usr.Name != 'CPQ User'){
                    Account acc = new Account();
                    acc.Name = country.substring(0, 3) + '_'+ 'Account'+'_'+ DateTime.now().millisecondGMT() + DateTime.now().minute() +DateTime.now().hour()+Date.today().day()+Date.today().month()+Date.today().year();
                    system.debug('Acc Name : '+ acc.Name);
                    acc.CurrencyIsoCode = 'USD';
                    acc.Subsidiary__c = 'HT US Newyork';
                    acc.ERPSystem__c = 'NetSuite';
                    acc.BillingCountry = country;
                    //acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName.get('Customer').getRecordTypeId();
                    acc.RecordTypeId = '0125w000000hxDwAAI';// customer record Type Id
                    acc.OwnerId = usr.Id;
                    system.debug('acc owner name : '+ usr.Name);
                    lstAccName.add(acc.Name);
                    lstAccToInsert.add(acc);
                } 
            }    
        }
        
        // Insert Accounts
        if(!lstAccToInsert.isEmpty()){
            //insert lstOppToInsert;
            Database.SaveResult[] srList = Database.insert(lstAccToInsert, false);
            for(Database.SaveResult sr : srList) {
                if(sr.isSuccess()){
                    // Operation was successful, so get the ID of the record that was processed
                    //System.debug('Successfully inserted account. Account ID: ' + sr.getId());
                    lstAccId.add(sr.getId());
                }
            }
        }
        
        /*
        2. Create opportunities and associate them with Accounts created above
        */ 
        list<Opportunity> lstOppToInsert = new list<Opportunity>();
        list<id> lstOppIds = new list<id>();
        list<string> lstOppName = new list<string>();
        list<string> lstOppTypes = new list<string>{'Existing Business', 'New Business', 'New Business / Add-on'};
        list<string> lstOppStage = new list<string>{'Prospecting', 'Closed Won', 'Proposal/Price Quote', 
            										'Qualification', 'Negotiation/Review'};
                
        // Query the Pricebook need to associate with Opportunity                                                
        Pricebook2 standardPriceBook = [select id from Pricebook2 where Name = 'Standard Price Book'];
        
        for(Account acc: [select id, Name, OwnerId from Account where id IN : lstAccId]){
            for(string oppStage: lstOppStage){
                Opportunity opp = new Opportunity();
                opp.Name = acc.Name + '_'+oppStage.substring(0, 3)+'_Opportunity';
                opp.AccountId = acc.Id;
                opp.StageName = oppStage;
                if(oppStage == 'Closed Won')
                    opp.CloseDate = date.today();
                opp.CloseDate = date.today().addDays(30);
                opp.OwnerId = acc.OwnerId;
                opp.Pricebook2Id = standardPriceBook.Id;
                opp.Type = lstOppTypes.get(Integer.valueof((Math.random() * (lstOppTypes.size()-1))));
                lstOppName.add(opp.Name);
                lstOppToInsert.add(opp);  
            }
        }
        
        // Insert Opportunity
        if(!lstOppToInsert.isEmpty()){
            //insert lstOppToInsert;
            Database.SaveResult[] srList = Database.insert(lstOppToInsert, false);
            for(Database.SaveResult sr : srList) {
                if(sr.isSuccess()){
                    // Operation was successful, so get the ID of the record that was processed
                    //System.debug('Successfully inserted account. Account ID: ' + sr.getId());
                    lstOppIds.add(sr.getId());
                }
            }
        }
        
        
        
        /*
        3. Create OpportunityProducts and associates them with Opportunities created above
        */ 
        
        // Query the list of Products in order to create Opportunity Products
        list<Product2> lstProduct = [select id, Name, CurrencyIsoCode, IsActive from Product2 where IsActive = true limit 1];
        list<OpportunityLineItem> lstOppLineItToInsert = new list<OpportunityLineItem>();
        
        for(Opportunity opp: [select id, Name from Opportunity where id in : lstOppIds]){
            for(Product2 pr: lstProduct){
                OpportunityLineItem oppLnIt = new OpportunityLineItem();
                oppLnIt.OpportunityId = opp.Id;
                //oppLnIt.Name = pr.Name;// not writeable
                oppLnIt.Product2Id = pr.Id;
                //oppLnIt.Quantity = (lstProduct.indexOf(pr) + 1);
                oppLnIt.Quantity = ((lstProduct.indexOf(pr) + 1) * 100);
                oppLnIt.TotalPrice = ((lstProduct.indexOf(pr) + 1) * 100);
                lstOppLineItToInsert.add(oppLnIt);
            }
        }
        
        //Insert OpportunityLineItems/OpportunityProducts
        if(!lstOppLineItToInsert.isEmpty()){
            insert lstOppLineItToInsert;
        }
        
        /*
        4. Create Primary Quotes and associates with Opportunities created above
        */
        
        list<string> lstQuoteStatuses = new list<string>{'Draft', 'In Review', 'Approved', 'Denied', 'Presented'};
        list<SBQQ__Quote__c> lstQuoteToInsert = new list<SBQQ__Quote__c>();
        list<id> lstQtcIds = new list<id>();
        
        for(Opportunity oppty: [select id, AccountId, OwnerId, StageName, Pricebook2Id from Opportunity where id in: lstOppIds]){
            SBQQ__Quote__c qt = new SBQQ__Quote__c();
            qt.SBQQ__Account__c = oppty.AccountId;
            qt.SBQQ__SalesRep__c = oppty.OwnerId;
            if(oppty.StageName == 'Clsoed Won'){
                qt.SBQQ__Status__c = 'Accepted'; 
            }else {
                qt.SBQQ__Status__c = lstQuoteStatuses.get(Integer.valueof((Math.random() * (lstQuoteStatuses.size()-1)))); 
            }
            qt.SBQQ__Opportunity2__c = Oppty.Id;
            qt.SBQQ__Primary__c = true;
            qt.SBQQ__PriceBook__c = Oppty.Pricebook2Id;
            
            lstQuoteToInsert.add(qt);
        }
        
        //Insert Quotes
        if(!lstQuoteToInsert.isEmpty()){
            //insert lstQuoteToInsert;
            SBQQ.TriggerControl.disable();
            Database.SaveResult[] srList = Database.insert(lstQuoteToInsert, false);
			SBQQ.TriggerControl.enable();		
            for(Database.SaveResult sr : srList) {
                if(sr.isSuccess()){
                    // Operation was successful, so get the ID of the record that was processed
                    //System.debug('Successfully inserted account. Account ID: ' + sr.getId());
                    lstQtcIds.add(sr.getId());
                }
            }
        }
        
       /*
        4. Create QuoteLineItems related to Primary Quotes created above
       */
        map<id, list<OpportunityLineItem>> mapOppIdToLstOppLnIt = new map<id, list<OpportunityLineItem>>();
        map<id, id> mapQuoteIdToOppId = new map<id, id>();
        map<id, id> mapProdIdToPriceBookEntryId = new map<id, id>();
        list<id> lstProductIds = new list<id>();
        list<SBQQ__QuoteLine__c> lstQuoLnItToInsert = new list<SBQQ__QuoteLine__c>();
        
        for(SBQQ__Quote__c qt: [select id,SBQQ__Opportunity2__c from SBQQ__Quote__c where id in: lstQtcIds]){
            mapQuoteIdToOppId.put(qt.id, qt.SBQQ__Opportunity2__c);
        }
        
        for(Opportunity opp: [select id, (select id, Product2Id, Product2.SBQQ__ChargeType__c, Quantity from OpportunityLineItems) from Opportunity where id in: mapQuoteIdToOppId.values()]){
            mapOppIdToLstOppLnIt.put(opp.id, opp.OpportunityLineItems);
            for(OpportunityLineItem oppLnIt: opp.OpportunityLineItems){
                lstProductIds.add(oppLnIt.Product2Id);
            }
        }
        
        for(PricebookEntry pe: [select id,Product2Id from PricebookEntry where Pricebook2.Name = 'Standard Price Book' and Product2Id in: lstProductIds]){
            mapProdIdToPriceBookEntryId.put(pe.Product2Id, pe.Id);
        }

        for(id quoteId: mapQuoteIdToOppId.keySet()){
            for(OpportunityLineItem oppLnIt: mapOppIdToLstOppLnIt.get(mapQuoteIdToOppId.get(quoteId))){
                SBQQ__QuoteLine__c QtLnIt = new SBQQ__QuoteLine__c();
                QtLnIt.SBQQ__Quote__c = quoteId;
                QtLnIt.SBQQ__Product__c = oppLnIt.Product2Id;
                QtLnIt.SBQQ__Quantity__c = oppLnIt.Quantity;
                QtLnIt.SBQQ__ChargeType__c = oppLnIt.Product2.SBQQ__ChargeType__c;
                QtLnIt.SBQQ__PricebookEntryId__c = mapProdIdToPriceBookEntryId.get(oppLnIt.Product2Id);
                lstQuoLnItToInsert.add(QtLnIt);
            }
        }

     	insert lstQuoLnItToInsert;
        
        
        /*
        5. Create Cases related to Accounts
        

        list<Case> lstCaseToInsert = new list<Case>();
        list<string> lstCaseStatuses = new list<string>{'On Hold', 'Escalated', 'Closed', 'New'};
        list<string> lstCaseDepartments= new list<string>{'Billing', 'Marketing', 'Renewal', 'Support', 'Service'};
        list<string> lstCaseTypes = new list<string>{'Problem','Feature Request','Question'};
        list<string> lstCaseOrigins = new list<string>{'Email','Phone','Web','Support Portal', 'NetSuite', 'Chat'};
        list<string> lstCaseReasons = new list<string>{'Complex Functionality','Existing Problem','New Problem','Instructions not clear'};
        
        for(Id accId: lstAccId){
                Case c = new Case();
                c.CurrencyIsoCode = 'USD';
                c.AccountId = accId;
                c.RecordTypeId = '0125w000000i6RFAAY';// RecordType : Dispute
                c.Status = lstCaseStatuses.get(Integer.valueof((Math.random() * (lstCaseStatuses.size()-1))));
                c.Origin = lstCaseOrigins.get(Integer.valueof((Math.random() * (lstCaseOrigins.size()-1))));
                c.Type = lstCaseTypes.get(Integer.valueof((Math.random() * (lstCaseTypes.size()-1))));
                c.Reason = lstCaseReasons.get(Integer.valueof((Math.random() * (lstCaseReasons.size()-1))));
                c.Department__c = lstCaseDepartments.get(Integer.valueof((Math.random() * (lstCaseReasons.size()-1))));
                if(c.Status == 'Closed'){
                    c.Agent_Satisfaction_Score__c = 7; 
                }    
                lstCaseToInsert.add(c); 
            }    
            
        //Insert Cases
        if(!lstCaseToInsert.isEmpty()){
            insert lstCaseToInsert;
        }
		*/
        
        /*
        6. Create Orders related to Opportunity, Accounts
        */
        list<Opportunity> lstOppsToUpdate_1= new list<Opportunity>();
        list<Opportunity> lstOppsToUpdate_2= new list<Opportunity>();
        map<id, id> mapOppIdToQtId = new map<id, id>();
        
        for(SBQQ__Quote__c qt: [select id ,SBQQ__Opportunity2__c, SBQQ__Opportunity2__r.StageName from SBQQ__Quote__c where SBQQ__Opportunity2__r.StageName = 'Closed Won' and id in: lstQtcIds]){
            mapOppIdToQtId.put(qt.SBQQ__Opportunity2__c, qt.id);
        }
        //[select count() from Opportunity where SBQQ__PrimaryQuote__c != null and id in: lstOppIds]
            
        system.debug('primary quote opportunity count: '+ [select count() from Opportunity where SBQQ__PrimaryQuote__c != null and id in: lstOppIds]);
        
        // update the closed won opportunities with ordered as true to generates the Orders
        for(Opportunity opp: [select id, StageName, SBQQ__Ordered__c, SBQQ__PrimaryQuote__c from Opportunity where id in: mapOppIdToQtId.keySet()]){
            opp.SBQQ__PrimaryQuote__c = mapOppIdToQtId.get(opp.id);
            opp.SBQQ__Ordered__c = true;
            lstOppsToUpdate_1.add(opp);
        }
        
        update lstOppsToUpdate_1;
        ///*
        /*system.debug('primary quote opportunity count: '+ [select count() from Opportunity where SBQQ__PrimaryQuote__c != null and id in: lstOppIds]);
        for(Opportunity opp: [select id, StageName, SBQQ__Ordered__c, SBQQ__PrimaryQuote__c from Opportunity where id in: mapOppIdToQtId.keySet()]){
            //opp.SBQQ__PrimaryQuote__c = mapOppIdToQtId.get(opp.id);
            opp.SBQQ__Ordered__c = true;
            lstOppsToUpdate_2.add(opp);
        }
        
        //update lstOppsToUpdate_2;
        */
        
        
        /*
        6. Create Contracts
        
        list<id> lstOrderIds = new list<id>();
        list<string> lstOrderTypes = new List<string>{'New', 'Amendment', 'Renewal'};
        list<Order> lstOrdersToUdpate = new list<Order>();
        
        list<Opportunity> lstOppsToUpdateToGenerateContracts = new list<Opportunity>();
        for(Order ord: [select id, AccountId, SBQQ__Quote__c from Order where AccountId in : lstAccId and SBQQ__Quote__c in : lstQtcIds]){
            ord.Status = 'Activated';
            ord.Type = lstOrderTypes.get(Integer.valueof((Math.random() * (lstOrderTypes.size()-1))));
            //ord.SBQQ__Contracted__c = true;
            lstOrdersToUdpate.add(ord);
        }
        
        //Update Orders
        update lstOrdersToUdpate;
        
        
        for(Opportunity opp: [select id, SBQQ__Contracted__c from Opportunity where id in: mapOppIdToQtId.keySet()]){
            opp.SBQQ__Contracted__c = true;
            lstOppsToUpdateToGenerateContracts.add(opp);
        }
        
        update lstOppsToUpdateToGenerateContracts;*/

		
    }
}