objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <formula>CASESAFEID(SBQQ__OrderProduct__r.OrderId)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscribed Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Asset.SBQQ__OrderProduct__r.OrderId,  Asset.SBQQ__OrderProduct__r.Order.OrderNumber )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>The last date this contract is valid.</description>
        <formula>if ( ISBLANK (SBQQ__SubscriptionEndDate__c), SBQQ__Contract__r.EndDate, SBQQ__SubscriptionEndDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The last date this contract is valid.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>The first date this subscription is in effect.</description>
        <formula>if ( ISBLANK (SBQQ__SubscriptionStartDate__c), SBQQ__Contract__r.StartDate, SBQQ__SubscriptionStartDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The first date this subscription is in effect.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateEntitlementHelper.cls
public class CreateEntitlementHelper {
    
    /*@future
    public static void createEntitlements(Set<Id> subscriptionIds,Set<Id> contractIds,Set<Id> productIds){
        
        set<Id> orderIds = new set<ID>();
        list<SBQQ__Subscription__c> subscriptionList = new list<SBQQ__Subscription__c>();
        list<Contract> listofContract = new list<Contract>();
        list<Asset> listofAsset = new list<Asset>();
        
        //SOQL on Subscription to get all new Subscriptoins
        subscriptionList = [select id,SBQQ__Product__c,SBQQ__Account__c,SBQQ__StartDate__c,SBQQ__EndDate__c from SBQQ__Subscription__c where id in: subscriptionIds];
        
        //SOQL on Contract to get Order Ids
         listofContract = [SELECT Id,SBQQ__Order__c FROM Contract WHERE Id =: contractIds];
         system.debug('listofContract****'+listofContract);
        //Create set of Order Ids
        for(Contract con:listofContract){
            
           orderIds.add(con.SBQQ__Order__c);
        }
         system.debug('orderIds****'+orderIds);
        //SOQL on Asset to get all Assets for Order Ids in previous step
        listofAsset = [Select id,Order__c from Asset  where Order__c =: orderIds];
        system.debug('listofAsset****'+listofAsset);
        
        list<Product2> listOfProduct = [SELECT Id, Name,Family FROM Product2 WHERE Id =: productIds ];
        Id entitlementProcessId      = [SELECT Id FROM SlaProcess WHERE SObjectType = 'Case'].Id;
        System.debug('entitlementProcessId= ' + entitlementProcessId);
        
        list<Entitlement> entList = new list<Entitlement>();
        //Iterate over Asset List
        for(Asset ass: listofAsset){
            for(SBQQ__Subscription__c  subcrp : subscriptionList){
                for(product2 pro :listOfProduct){
                    if(pro.Id == subcrp.SBQQ__Product__c  && pro.Family =='Support'){
                        Entitlement entl = new Entitlement();
                        entl.Name        = 'Entitlement for Product: '+ pro.Name;
                        entl.AccountId   = subcrp.SBQQ__Account__c;
                        entl.Startdate   = subcrp.SBQQ__StartDate__c;
                        entl.Enddate     = subcrp.SBQQ__EndDate__c;
                        entl.SlaProcessId= entitlementProcessId;
                        entl.AssetId =  ass.Id;
                        entList.add(entl);
                    }
                }
            }
        }
        
        if(entList.size()>0){
            system.debug('entList****'+entList);
            insert entList;
        }
        System.debug(entList);
    }*/
    
}