objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this Opportunity Product.</description>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>OpportunityProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__ChargeType__c</fullName>
        <description>The type of the product charge.</description>
        <inlineHelpText>The type of the product charge.</inlineHelpText>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__ChargeType</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__ChargeType__c</fullName>
        <description>The type of the product charge.  This is a system field that is derived from the associated product.</description>
        <inlineHelpText>The type of the product charge.  This is a system field that is derived from the associated product.</inlineHelpText>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__ChargeType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__PricebookEntryId__c</fullName>
        <label>Pricebook Entry Id</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteLineItDataLoadBatch.cls
public class QuoteLineItDataLoadBatch implements Database.Batchable<SObject>,Database.Stateful{
    string query;
    list<id> lstQtcIds;
    
    map<id, list<OpportunityLineItem>> mapOppIdToLstOppLnIt = new map<id, list<OpportunityLineItem>>();
        map<id, id> mapQuoteIdToOppId = new map<id, id>();
        map<id, id> mapProdIdToPriceBookEntryId = new map<id, id>();
        list<id> lstProductIds = new list<id>();
        list<SBQQ__QuoteLine__c> lstQuoLnItToInsert = new list<SBQQ__QuoteLine__c>();
    
    /**
     * Constructor to prepare the query.
     * @Params: list<id> lstOppIds
     * @Output: NA.
    */
    public QuoteLineItDataLoadBatch(list<id> lstQtcIds){
    	this.lstQtcIds = lstQtcIds;

        query = 'Select Id, SBQQ__Opportunity2__c' +
                ' From SBQQ__Quote__c' +
                ' Where Id IN: lstQtcIds'; 
        System.debug('#query' + query);
    }
    
    /**
     * Batch's start method to query records.
     * @Params: NA
     * @Output: list<Opportunity>
    */
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }
    
    /**
     * Batch's execute method to create Opportunities.
     * @Params: List<Opportunity>
     * @Output: void
    */
    public void execute(Database.BatchableContext bc, list<SBQQ__Quote__c> lstQuotes){	
        
        
        for(SBQQ__Quote__c qt: lstQuotes){
            mapQuoteIdToOppId.put(qt.id, qt.SBQQ__Opportunity2__c);
        }
        
        for(Opportunity opp: [select id, (select id, Product2Id, Product2.SBQQ__ChargeType__c, Quantity from OpportunityLineItems) from Opportunity where id in: mapQuoteIdToOppId.values()]){
            mapOppIdToLstOppLnIt.put(opp.id, opp.OpportunityLineItems);
            for(OpportunityLineItem oppLnIt: opp.OpportunityLineItems){
                lstProductIds.add(oppLnIt.Product2Id);
            }
        }
        
        for(PricebookEntry pe: [select id,Product2Id from PricebookEntry where Pricebook2.Name = 'Standard Price Book' and Product2Id in: lstProductIds]){
            mapProdIdToPriceBookEntryId.put(pe.Product2Id, pe.Id);
        }

        for(id quoteId: mapQuoteIdToOppId.keySet()){
            for(OpportunityLineItem oppLnIt: mapOppIdToLstOppLnIt.get(mapQuoteIdToOppId.get(quoteId))){
                SBQQ__QuoteLine__c QtLnIt = new SBQQ__QuoteLine__c();
                QtLnIt.SBQQ__Quote__c = quoteId;
                QtLnIt.SBQQ__Product__c = oppLnIt.Product2Id;
                QtLnIt.SBQQ__Quantity__c = oppLnIt.Quantity;
                QtLnIt.SBQQ__ChargeType__c = oppLnIt.Product2.SBQQ__ChargeType__c;
                QtLnIt.SBQQ__PricebookEntryId__c = mapProdIdToPriceBookEntryId.get(oppLnIt.Product2Id);
                lstQuoLnItToInsert.add(QtLnIt);
            }
        }

     	insert lstQuoLnItToInsert;
    }
    // 
    
    /**
     * Batch's finish method.
     * @Params: NA
     * @Output: void
    */
    public void finish(Database.BatchableContext bc){
        //Database.executeBatch(new OpptyLnItDataLoadBatch(lstOppIds));
    }
}