objects/ProductRecommendation__c.object
<CustomObject>
    <description>Product Recommendation for Salesforce CPQ</description>
    <fields>
        <fullName>Product2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Product Object</description>
        <label>Product2Id</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ProductRecommendations</relationshipLabel>
        <relationshipName>ProductRecommendations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecommendedProduct2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for Recommended Product to Project Object</description>
        <label>RecommendedProduct2Id</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ProductRecommendations (RecommendedProduct2Id)</relationshipLabel>
        <relationshipName>ProductRecommendations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ProductRecommendation</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>ProductRecommendation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProductRecommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProductRecommendationPluginClass.cls
global class ProductRecommendationPluginClass implements SBQQ.ProductRecommendationPlugin{
global ProductRecommendationPluginClass() {
}
global PricebookEntry[] recommend(SObject quote, List<SObject> quoteLines) {
    
    // Get the price book Id of the quote
    Id pricebookId = (Id)quote.get('SBQQ__PriceBookId__c');
    String quoteCurrency=(String)quote.get('CurrencyIsoCode');

    // Get Ids of all products in the quote
    Id[] productIdsInQuote = new Id[0];
    for (SObject quoteLine : quoteLines) {
        Id productId = (Id)quoteLine.get('SBQQ__Product__c');
        productIdsInQuote.add(productId);
    }

    // Query the recommendation custom object records of all products in quote.
   ProductRecommendation__c[] recommendations = [
        SELECT RecommendedProduct2Id__c
        FROM ProductRecommendation__c
        WHERE Product2Id__c IN :productIdsInQuote];

    // Get Ids of all recommended products
    Id[] recommendedProductIds = new Id[0];
    for(ProductRecommendation__c recommendation : recommendations) {
        recommendedProductIds.add(recommendation.RecommendedProduct2Id__c);
    }
    
    // Query the price book entries of the above recommended products
    PricebookEntry[] priceBookEntries = [
        SELECT Id, UnitPrice, Pricebook2Id, Product2Id, Product2.Name, Product2.ProductCode
        FROM PricebookEntry
        WHERE Product2Id IN :recommendedProductIds AND Pricebook2Id = :pricebookId AND CurrencyIsoCode=:quoteCurrency];
       
    return priceBookEntries;
}
}