objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__SalesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales rep responsible for this quote if different from the user who owns the quote record.</description>
        <inlineHelpText>Sales rep responsible for this quote if different from the user who owns the quote record.</inlineHelpText>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QuoteDataLoadBatch.cls
public class QuoteDataLoadBatch implements Database.Batchable<SObject>,Database.Stateful{
    string query;
    list<id> lstOppIds;
    
    list<string> lstQuoteStatuses = new list<string>{'Draft', 'In Review', 'Approved', 'Denied', 'Presented'};
    list<SBQQ__Quote__c> lstQuoteToInsert = new list<SBQQ__Quote__c>();
    list<id> lstQtcIds = new list<id>();
    
    /**
     * Constructor to prepare the query.
     * @Params: list<id> lstOppIds
     * @Output: NA.
    */
    public QuoteDataLoadBatch(list<id> lstOppIds){
    	this.lstOppIds = lstOppIds;

        query = 'Select Id, AccountId, OwnerId, StageName' +
                ' From Opportunity' +
                ' Where Id IN: lstOppIds'; 
        System.debug('#query' + query);
    }
    
    /**
     * Batch's start method to query records.
     * @Params: NA
     * @Output: list<Opportunity>
    */
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }
    
    /**
     * Batch's execute method to create Opportunities.
     * @Params: List<Opportunity>
     * @Output: void
    */
    public void execute(Database.BatchableContext bc, list<Opportunity> lstOpps){	
        
        for(Opportunity oppty: lstOpps){
            SBQQ__Quote__c qt = new SBQQ__Quote__c();
            qt.SBQQ__Account__c = oppty.AccountId;
            qt.SBQQ__SalesRep__c = oppty.OwnerId;
            if(oppty.StageName == 'Clsoed Won'){
                qt.SBQQ__Status__c = 'Accepted'; 
            }else {
                qt.SBQQ__Status__c = lstQuoteStatuses.get(Integer.valueof((Math.random() * (lstQuoteStatuses.size()-1)))); 
            }
            qt.SBQQ__Opportunity2__c = Oppty.Id;
            qt.SBQQ__Primary__c = true;
            
            lstQuoteToInsert.add(qt);
        }
        // disable the sbqq managed package trigger
        SBQQ.TriggerControl.disable();
        // Insert Opportunities
        Database.SaveResult[] srList = Database.insert(lstQuoteToInsert, false);
        
        // Enable the sbqq managed package trigger
        SBQQ.TriggerControl.enable();
        
        // Iterate through each returned result
        for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                //System.debug('Successfully inserted account. Account ID: ' + sr.getId());
                lstQtcIds.add(sr.getId());
            }
        }
    }
    // 
    
    /**
     * Batch's finish method.
     * @Params: NA
     * @Output: void
    */
    public void finish(Database.BatchableContext bc){
        Database.executeBatch(new QuoteLineItDataLoadBatch(lstQtcIds));
    }
}