objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Payment_Mode__c</fullName>
        <label>Payment Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Arrear Payments</fullName>
                </value>
                <value>
                    <fullName>Advancement payments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__NetAmount__c</fullName>
        <description>Total Net Amount of each non-optional line item in this quote.</description>
        <inlineHelpText>Total Net Amount of each non-optional line item in this quote.</inlineHelpText>
        <label>Net Amount</label>
        <summarizedField>SBQQ__QuoteLine__c.SBQQ__NetTotal__c</summarizedField>
        <summaryFilterItems>
            <field>SBQQ__QuoteLine__c.SBQQ__Optional__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FetchHomePageMessagesController.cls
public class FetchHomePageMessagesController {
    
    @AuraEnabled
    public static String fetchQuoteRecord(){
        
        Id userId = UserInfo.getUserId();
        List<User> lstUser = [Select Id,Name,ContactId from User WHERE Id = :userId LIMIT 1];
         system.debug('lstUser '+lstUser[0]);	
         system.debug('UserName '+lstUser[0].Name);          
        
        List<SBQQ__Quote__c> quoteList = [SELECT Id, Name,SBQQ__PrimaryContact__c, SBQQ__PrimaryContact__r.Name,Payment_Mode__c,
                                          SBQQ__NetAmount__c
                                          FROM SBQQ__Quote__c 
                  						  WHERE SBQQ__PrimaryContact__c =: lstUser[0].ContactId
                                          AND Payment_Mode__c !=null];
        
        system.debug('quoteList '+quoteList);
       
        if(!quoteList.isEmpty() && quoteList[0].Payment_Mode__c == 'Arrear Payments'){
            return 'Arrear';
        }
        else if(!quoteList.isEmpty() && quoteList[0].Payment_Mode__c == 'Advancement payments'){
            return 'Advancement';
        }
        return null;
           
    }

}